{% set version = "0.1.9" %}

package:
  name: mi-fieldcalc
  version: {{ version }}

source:
  url: https://github.com/metno/mi-fieldcalc/archive/v{{ version }}.tar.gz
  sha256: cc2485b30813db95fcd380c3846d3b5d044162eb4e853a45c1f18296b7ae49e8
  folder: source

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - cmake
    - make         # [not win]
    - ninja        # [win]
  host:
    - python
    - numpy
    - pybind11 >=2.2
    - pybind11-abi
  run:
    - python
    - _openmp_mutex

test:
  commands:
    - test -f $PREFIX/include/mi_fieldcalc/FieldCalculations.h  # [unix]
    - test -f $PREFIX/lib/libmi-fieldcalc$SHLIB_EXT  # [unix]
  imports:
    - mi_fieldcalc

about:
  home: https://github.com/metno/mi-fieldcalc
  license: GPL-2.0-or-later
  license_file: source/LICENSE.txt
  summary: 'MET Norway field calculations library'

extra:
  recipe-maintainers:
    - alexander-buerger-met-no
    - audunc
    - lisbethb-met-no
